service: image-recognition

frameworkVersion: ">=1.36.3 <2.0.0"

custom:
  bucket: tmp-image-recognition

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - rekognition:Detect*
      Resource: "*"

functions:
  recognizeUpdatedImages:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
    environment:
      BUCKET: ${self:custom.bucket}

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}